/**
 * Server-side card pool (contracts/card-pool.json, generated by
 * scripts/gen-card-pool.mjs from public/data/cards.json).
 *
 * Used for starter-squad grants, match reward pulls and scout pulls.
 * Where the pool lacks enough cards for a rarity/position bucket (the sample
 * database has ~76 cards), all draws degrade gracefully to the nearest
 * available bucket.
 */
import poolJson from "../../contracts/card-pool.json";

export type Rarity =
  | "REG"
  | "SPE"
  | "RAR"
  | "WBE"
  | "WGK"
  | "MVP"
  | "ATLE"
  | "YS";

export interface CardPoolEntry {
  id: string;
  name: string;
  rarity: Rarity;
  positions: string[];
  version: string;
}

export const CARD_POOL = poolJson as CardPoolEntry[];

const BY_RARITY = new Map<Rarity, CardPoolEntry[]>();
for (const card of CARD_POOL) {
  const bucket = BY_RARITY.get(card.rarity) ?? [];
  bucket.push(card);
  BY_RARITY.set(card.rarity, bucket);
}

/** Rarity ladder used to fall back to the "nearest available" bucket. */
const RARITY_ORDER: Rarity[] = [
  "REG",
  "SPE",
  "RAR",
  "YS",
  "WBE",
  "WGK",
  "MVP",
  "ATLE",
];

function nearestAvailable(rarity: Rarity): CardPoolEntry[] {
  const exact = BY_RARITY.get(rarity);
  if (exact && exact.length > 0) return exact;
  const at = RARITY_ORDER.indexOf(rarity);
  for (let step = 1; step < RARITY_ORDER.length; step++) {
    // walk toward common rarities first, then toward rarer ones
    const lower = RARITY_ORDER[at - step];
    if (lower) {
      const b = BY_RARITY.get(lower);
      if (b && b.length > 0) return b;
    }
    const upper = RARITY_ORDER[at + step];
    if (upper) {
      const b = BY_RARITY.get(upper);
      if (b && b.length > 0) return b;
    }
  }
  return CARD_POOL;
}

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

/** Draw one card of `rarity` (nearest available bucket on thin pools). */
export function drawCard(rarity: Rarity): CardPoolEntry {
  return pick(nearestAvailable(rarity));
}

/**
 * Weighted rarity draw. Weights for buckets that are empty in the pool are
 * redistributed to the nearest available rarity so probabilities still sum
 * to 1 over drawable cards.
 */
export function drawWeighted(weights: Partial<Record<Rarity, number>>): CardPoolEntry {
  const entries = Object.entries(weights).filter(
    (entry): entry is [Rarity, number] => (entry[1] ?? 0) > 0,
  );
  const total = entries.reduce((a, [, w]) => a + w, 0);
  let roll = Math.random() * total;
  for (const [rarity, w] of entries) {
    roll -= w;
    if (roll <= 0) return drawCard(rarity);
  }
  const last = entries[entries.length - 1];
  return drawCard(last ? last[0] : "REG");
}

/** Match reward rarity weights (backend-spec §match.report). */
export const REWARD_WEIGHTS: Record<Rarity, number> = {
  REG: 0.62,
  SPE: 0.25,
  RAR: 0.09,
  YS: 0.02,
  WBE: 0.01,
  WGK: 0.005,
  MVP: 0.005,
  ATLE: 0.005,
};

export function drawRewardCard(): CardPoolEntry {
  return drawWeighted(REWARD_WEIGHTS);
}

/* ------------------------------------------------------------------ */
/* Starter squad (18 cards: 14 REG, 3 SPE, 1 RAR; 2 GK 6 DF 6 MF 4 FW) */
/* ------------------------------------------------------------------ */

type PositionGroup = "GK" | "DF" | "MF" | "FW";

const GROUP_POSITIONS: Record<PositionGroup, string[]> = {
  GK: ["GK"],
  DF: ["CB", "LSB", "RSB"],
  MF: ["DMF", "CMF", "OMF", "SMF"],
  FW: ["FW", "CF"],
};

function shuffled<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

/**
 * Deal the 18-card starter squad: position-balanced (2 GK, 6 DF, 6 MF, 4 FW)
 * with rarity split 14 REG / 3 SPE / 1 RAR. Cards are unique within the
 * squad; thin buckets fall back to the nearest available rarity/position.
 */
export function dealStarterSquad(): CardPoolEntry[] {
  const groups = shuffled([
    ...Array<PositionGroup>(2).fill("GK"),
    ...Array<PositionGroup>(6).fill("DF"),
    ...Array<PositionGroup>(6).fill("MF"),
    ...Array<PositionGroup>(4).fill("FW"),
  ]);
  const rarities = shuffled([
    ...Array<Rarity>(14).fill("REG"),
    ...Array<Rarity>(3).fill("SPE"),
    ...Array<Rarity>(1).fill("RAR"),
  ]);

  const used = new Set<string>();
  const squad: CardPoolEntry[] = [];

  for (let i = 0; i < groups.length; i++) {
    const group = groups[i];
    const wanted = rarities[i];
    // candidates: right rarity ladder bucket, right position group, unused
    let bucket = nearestAvailable(wanted).filter(
      (c) =>
        !used.has(c.id) &&
        c.positions.some((p) => GROUP_POSITIONS[group].includes(p)),
    );
    if (bucket.length === 0) {
      // degrade: any rarity covering the position group
      bucket = CARD_POOL.filter(
        (c) =>
          !used.has(c.id) &&
          c.positions.some((p) => GROUP_POSITIONS[group].includes(p)),
      );
    }
    if (bucket.length === 0) {
      // last resort: any unused card
      bucket = CARD_POOL.filter((c) => !used.has(c.id));
    }
    if (bucket.length === 0) break; // pool exhausted (never with ≥18 cards)
    const card = pick(bucket);
    used.add(card.id);
    squad.push(card);
  }
  return squad;
}
